// Mock shipping options data for testing
export const MOCK_SHIPPING_OPTIONS = [
  {
    id: '36016876',
    carrier: 'Carrier TBN',
    indicative: true,
    container: '20ST',
    transitDays: 27,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Los Angeles, US',
    toPort: 'Los Angeles',
    via: 'Casablanca',
    price: 4436,
    currency: 'USD',
    rateStatus: 'Indicative'
  },
  {
    id: '36016875',
    carrier: 'Carrier TBN',
    indicative: true,
    container: '20ST',
    transitDays: 25,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Long Beach, US',
    toPort: 'Long Beach',
    via: 'Casablanca',
    price: 4582,
    currency: 'USD',
    rateStatus: 'Indicative'
  },
  {
    id: '36016874',
    carrier: 'Maersk Line',
    indicative: false,
    container: '20ST',
    transitDays: 23,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Los Angeles, US',
    toPort: 'Los Angeles',
    price: 4125,
    currency: 'USD',
    rateStatus: 'Confirmed'
  },
  {
    id: '36016873',
    carrier: 'CMA CGM',
    indicative: false,
    container: '20ST',
    transitDays: 29,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Los Angeles, US',
    toPort: 'Los Angeles',
    via: 'Barcelona',
    price: 4890,
    currency: 'USD',
    rateStatus: 'Confirmed'
  },
  {
    id: '36016872',
    carrier: 'MSC',
    indicative: true,
    container: '20ST',
    transitDays: 26,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Long Beach, US',
    toPort: 'Long Beach',
    price: 4320,
    currency: 'USD',
    rateStatus: 'Indicative'
  },
  {
    id: '36016871',
    carrier: 'Hapag-Lloyd',
    indicative: false,
    container: '20ST',
    transitDays: 24,
    from: 'Tangier, MA',
    fromPort: 'Tangier',
    to: 'Los Angeles, US',
    toPort: 'Los Angeles',
    price: 4650,
    currency: 'USD',
    rateStatus: 'Confirmed'
  }
];
