export const DUMMY_SHIPMENT = {
  mode: "sea",
  shipmentType: "FCL",
  containerType: "20ST",
  pol: "Tangier, MA",
  pod: "Los Angeles, US",
  plorChecked: true,
  plor: "Tangier Free Zone Warehouse",
  plodChecked: true,
  plod: "Los Angeles Inland Depot",
  cargoType: "General",
  commodity: "Electronics",
  grossWeight: 12000,
  pickupLocation: "Tangier, MA",
  wizardSelection: {
    mainCategory: "Standard Shipping",
    subCategory: "Door to Port",
  },
  coldTreatment: {
    required: false,
    temperature: "",
    temperatureSetPoints: [],
    multipleSetPoints: false,
  },
  probes: {
    numberOfCargoProbes: 0,
    drainHoles: false,
    freshAirExchange: "open",
    ventilationVolume: "",
  },
  humidity: {
    required: false,
    percentage: "",
  },
  genset: {
    duringExport: false,
    duringImport: false,
  },
  temperatureSchedule: {
    daysBeforeETA: [],
    daysAfterGateIn: [],
  },
  cargo: {
    class: "",
    unNumber: "",
    width: "",
    length: "",
    height: "",
    lengthMetrics: "meter",
    packageType: "Pallet",
    numberOfPackages: 10,
    volume: "25",
    truckType: "Standard",
    numberOfPallets: 10,
    stackableCargo: true,
  },
  liftgate: { required: false },
  accsesConditions: "",
  price: 4125,
};
